### ISSUE TITLE
Package on Pypi

### ISSUE THREAD

**Issue by CharlesParent** [eveybcd/x13bcd_hash#2]
Hello,

I'm trying to build electrumbcd on Windows, and I have trouble when building package as x13bcd_hash package is not available on Pypi (only sources), forcing the build to build it from source.

Could it be possible for anyone to deploy a package on PyPi for windows ?

Thank you in advance for your answer

**Comment by Starry9** [comment]
Sorry, we known that x13bcd_hash is not available for windows on pypi, and we suggest to build it from source on windows system.
